# suppress inspection "UnusedProperty" for whole file
debug=true

spring.mvc.log-request-details=true
logging.level.web=debug
logging.level.security=debug
logging.level.sql=debug

spring.security.user.name=test
spring.security.user.password=test